### ISSUE TITLE
Unable to open preferences: org.gnome.shell.extensions.screenshotlocations.data.gresource - No such file or directory

### ISSUE THREAD

**Issue by szpak** [TimurKiyivinski/gnome-shell-screenshotlocations-extension#13] opened 2020-10-11 10:50 UTC
In master version (with #11), after compiling schemas there is a problem with opening the preferences dialog:

```
GLib.FileError: Failed to open file “/home/foobar/.local/share/gnome-shell/extensions/screenshotlocations.timur@linux.com/org.gnome.shell.extensions.screenshotlocations.data.gresource”: open() failed: No such file or directory

Stack trace:
  @/home/foobar/.local/share/gnome-shell/extensions/screenshotlocations.timur@linux.com/prefs.js:31:37
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by szpak** [comment] 2020-10-11 11:06
It turned out to be similar to #12:
> glib-compile-resources org.gnome.shell.extensions.screenshotlocations.data.gresource.xml

**Comment by kiyui** [comment] 2020-10-12 02:15
Duplicate of #12

**Closed as completed by kiyui** 2020-10-12 02:15 UTC
